language: cpp

os:
  - linux
  - osx

env:
  - variant=test_debug
  - variant=test_release
  - variant=test_barebones

compiler:
  - gcc
  - clang

# container-based builds
sudo: false
cache:
  directories:
    - $HOME/.ccache

# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.9
    - libboost1.55-all-dev
    - boost-build
    - python2.7-dev

before_install:
  - git submodule update --init --recursive

install:
  - 'echo "using gcc : : ccache g++-4.9 : <cxxflags>-std=c++11 ;" > ~/user-config.jam'
  - 'echo "using clang : : ccache clang++ : <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
  - 'echo "using python : 2.7 ;" >> ~/user-config.jam'
  - ccache -V && ccache --show-stats && ccache --zero-stats
  - which $CXX-4.9
  - ls -la `which $CXX-4.9`

script:
  - cd test
  - b2 -j 3 variant=$variant warnings=off -l900 $CC
  - cd ../examples
  - b2 -j 3 variant=$variant warnings=off $CC
  - cd ../bindings/python
  - b2 -j 3 variant=$variant warnings=off $CC stage_module
  - LD_LIBRARY_PATH=. python test.py
  - cd ../../simulation
  - b2 -j 3 variant=$variant warnings=off $CC
  - ccache --show-stats

